### ISSUE TITLE
The override decorator is required on anonymous classes, even though they're invalid

### ISSUE THREAD

**Issue by ChiriVulpes** [hmil/tslint-override#24]
Decorators are invalid in anonymous classes. As a result, when this rule is configured to use decorator-style override marking, this rule will warn & and try to make a fix that causes an error.

There probably should be some kind of additional option for anonymous classes that only has an effect when "decorator" is provided. For example, maybe an "anonymous-classes-jsdoc" or "anonymous-classes-ignore", defaulting to one or the other. (I would lean towards just "ignore" as default, personally)

example code:
```ts
abstract class Foo {
	public bar = 0;
}

const Fiz = new class extends Foo {
	public bar = 1;
};
```

Fixes to:
```ts
const Fiz = new class extends Foo {
	@Override public bar = 1; // errors
};
```

**Comment by hmil** [comment]
Interesting use-case. I wasn't aware that decorators are not allowed in anonymous classes.

**Comment by ChiriVulpes** [comment]
Thanks for the quick turnaround!
