### ISSUE TITLE
npm install does not install rules directory

### ISSUE THREAD

**Issue by stasberkov** [hmil/tslint-override#9]
`npm install` does not install rules directory as result feature does not work.

**Comment by hmil** [comment]
Oh man, I messed up the travis config in my last patch. Thanks for calling it out!
Version 0.2.5 should work. Let me know if you have another issue.

**Comment by hmil** [comment]
Notice that the latest release of VSCode broke `tslint-language-service`, so error reporting within VSCode will likely not work at the moment.
https://github.com/angelozerr/tslint-language-service/issues/76

**Comment by stasberkov** [comment]
Cool! Thank you for fast fix!
